version: '3'
services:
  nginx:
    image: nginx:1.14-alpine
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./www:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  php:
    image: php:7.3.0-fpm-alpine3.8
    user: "82:82"
    volumes:
      - ./www:/app
      - ./www:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /app